---
- name: Add Google Chrome repository on Debian family
  ansible.builtin.shell: |
    curl -fsSL https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor | tee /etc/apt/keyrings/google-archive-keyring.gpg >/dev/null
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/google-archive-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list > /dev/null
  args:
    creates: /etc/apt/keyrings/google-archive-keyring.gpg

- name: Add Brave repository on Debian family
  ansible.builtin.shell: |
    curl -fsSLo /etc/apt/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list > /dev/null
  args:
    creates: /etc/apt/keyrings/brave-browser-archive-keyring.gpg

- name: Update apt cache for new repositories
  ansible.builtin.apt:
    update_cache: true
